# Generated by Django 2.2.2 on 2019-10-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品种类', 'verbose_name_plural': '商品种类'},
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='df_goods_type',
        ),
    ]
